"""add column head_picture string120

Revision ID: aec93de9e9b2
Revises: 816ded05254d
Create Date: 2017-11-09 17:09:31.278000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aec93de9e9b2'
down_revision = '816ded05254d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'head_picture', sa.String(length=120), existing_type=mysql.VARCHAR(120))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'head_picture', sa.String(length=100), existing_type=mysql.VARCHAR(100))
    # ### end Alembic commands ###
